name: CD Example Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: CD Example Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout My Code
        uses: actions/checkout@v4 # Checkout the repository

      - name: SSH Connect
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Berhasil terkoneksi dengan server"
            if [ -d "/home/cicd" ]; then
              echo "Ada folder cicd"
              cd /home/cicd
            else
              echo "Tidak ada folder cicd, membuat folder cicd"
              mkdir /home/cicd
              cd /home/cicd
            fi

            if [-d ".git" ]; then
              echo "Ada folder .git, melakukan git pull..."
              git remote set-url origin ${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PAT }}@github.com/${{ secrets.GIT_USERNAME }}/cicd_database_example.git
              git pull origin main
            else
              echo "Tidak ada folder .git, melakukan git clone"
              git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PAT }}@github.com/${{ secrets.GIT_USERNAME }}/cicd_database_example.git .
            fi

            echo "Berhasil deploy aplikasi ke server"
