name: CICD Database Dev to Prod

on:
  push:
    branches:
      - main

jobs:
  db_cicd:
    name: Database CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 #Checkout ke repository yang digunakan
      - name: SSH Connect
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Berhasil konek ke server"

            cd /home/cicd
            echo "Berhasil masuk ke folder cicd"

            sudo docker compose up -d  #Menjalankan docker compose di server
            echo "Berhasil menjalankan docker compose"
